#!/usr/bin/env bash

echo "--> Cleaning up package status"
apt-get update

echo "--> Installing Read The Docs infrastructure"
apt-get install -y \
	python-dev \
	python-pip \
	nginx
pip install \
	sphinx \
	recommonmark \
	breathe

echo "--> Setting up web server"
cp /vagrant/provision/nginx.conf /etc/nginx/sites-available/site.conf
chmod 644 /etc/nginx/sites-available/site.conf
ln -s /etc/nginx/sites-available/site.conf /etc/nginx/sites-enabled/site.conf
service nginx start
