#!/usr/bin/env bash

echo "--> Cleaning up package status"
apt-get update

echo "--> Installing Read The Docs infrastructure"
apt-get install -y \
	doxygen \
	nginx \
	python-dev \
	python-pip
pip install \
	breathe \
	recommonmark \
	sphinx \
	sphinx_rtd_theme

echo "--> Setting up web server"
cp /vagrant/provision/nginx.conf /etc/nginx/sites-available/site.conf
chmod 644 /etc/nginx/sites-available/site.conf
ln -s /etc/nginx/sites-available/site.conf /etc/nginx/sites-enabled/site.conf
service nginx start

echo "--> Setting up virtual-machine info"
echo "monodocs" > /etc/debian_chroot
